config/routes.rb
CaptainsLog::Application.routes.draw do

  root to: "questions#index"

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :answers, only: [] do
    resources :votes, only: [:create]
  end

  resources :questions, only: [] do
    resources :votes, only: [:create]
  end

  resources :questions, only: [] do
    resources :answers, only: [:create]
  end

  resources :questions, only: [:new, :show, :create]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :user_id, :question_id, :description
  belongs_to :user
  belongs_to :question
  has_many :votes, as: :votable

  validates :description, :user, :question, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :description
  belongs_to :user
  has_many :answers
  has_many :votes, as: :votable

  validates :title, :description, :user, presence: true

  def vote_tally
    self.votes.map(&:up?).count - self.votes.map(&:down?).count
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :name, :email, :password
  has_many :questions
  has_many :answers
  has_many :votes

  has_secure_password

  validates :name, :email, :password, presence: true
  validates :email, format: /\w+@\w+\.\w+/
  validates :email, uniqueness: true

  before_save :create_remember_token

  private

  def create_remember_token
  	self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :up, :down, :votable_id, :votable_type, :user

  belongs_to :votable, polymorphic: true
  belongs_to :user

  validates :user_id, :votable_id, :votable_type, presence: true
  validates_uniqueness_of :user_id, scope: [:votable_type, :votable_id]

  # REVIEW: refactor this.
  def change_vote(click_value)
    key = click_value.key("true")
    if !self.up && !self.down
      self[key] = true
    elsif self.up && !self.down
      self.up = false if key == "down"
    else
      self.down = false if key == "up"
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # REVIEW: user authenticate_user
  def create
    @question = Question.find(params[:question_id])
    @answer = current_user.answers.build params[:answer]
    @answer.question = @question
    if @answer.save
      # happy path
    else
      # unhappy path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include Authentication

  helper_method :current_user, :signed_in?

  # REVIEW: where does this come from?
  def handle_unverified_request
  	sign_out
  	super
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    puts flash[:notices] # REVIEW: please dont commit debugging code.
    @notices = flash[:notices] # REVIEW: you have access to flash in the views, no need for the variable.
    @questions = Question.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user, :only => [:new, :create]
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build params[:question]
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user
    else
      flash[:notice] = @user.errors.full_messages.join(". ")
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
    # REVIEW: my strong opinion, these variables are not needed. use @user.questions in the view.
    @questions = @user.questions
    @answers = @user.answers
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_filter :load_votable

  def create
    create_vote
  end

  private

  def load_votable
    resource, id = request.path.split('/')[1, 2]
    @votable = resource.singularize.classify.constantize.find(id)
  end

  # this needs some serious refactoring, too much logic
  def create_vote
    # user authenticate_user
    if signed_in?
      current_user.voted?(votable)
      vote = Vote.where(user_id: current_user.id, votable_type: @votable.class, votable_id: @votable.id)
      button = params[:vote]
      if vote.empty?
        vote = @votable.votes.new(user: current_user)
      else
        vote = vote.first
      end
      vote.change_vote(button)
      unless vote.save
        flash_error = vote.errors.full_messages.join(', ')
        render json: { flash_error: flash_error }, status: :unprocessable_entity
      end
    end
    render json: { vote_count: vote_tally(@votable) }
  end

  def votable
    @votable.is_a?(Question) ? @votable : @votable.question
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/questions_helper.rb
module QuestionsHelper
	def vote_tally(topic)
		topic.vote_tally
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper



end

app/views/home/index.html.erb
REVIEW: formatting and indentation sucks
<div>
<br>
<% if  @notices %>
  <%= @notices %>
<% end %>

<h3>
<%= link_to "Create new question", new_question_path, class: "create_question" %>
</h3>
<br>
<h3>
Or...
</h3>
<br>
<h3>
Answer Questions:
</h3>
<% @questions.each do |question| %>

  <%= link_to question.title, question, class: "question_link" %>
  <br>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="/">Captain's Log</a>
   
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '/' %></li>
      <li><%= link_to "Contact", '/' %></li>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container nav", id="nav">

      <%= link_to image_tag('logov1.png'), root_path, :class => 'navbar-brand' %>

      <% provide(:title, "Sign in") %>    
     
      <%= form_tag sessions_path, :class => 'navbar-form pull-right' do %>
        <% if signed_in? %>
          <%= link_to "Sign out", signout_path, method: "delete", :class => "btn btn-danger", :id => 'signout' %>
          <%= link_to "Profile", user_path(current_user), :class => "btn btn-info" %>  
        <% else %>
          <%= text_field_tag(:email, nil, placeholder: "Email", class: 'form-control') %>
          <%= text_field_tag(:password, nil, placeholder: "Password", type: 'password', class: 'form-control') %>
          <%= submit_tag("Sign In", :class => 'btn btn-success', :id => 'sign_in') %>
        <%end%>
      <% end %>
      <% if !signed_in? %>
        <a class="btn btn-primary" href="#" id="modal_link"> Sign Up </a>

      <%end%>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaptainsLog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
  <%= render 'layouts/header' %>
  <% if flash %>
    <%= render 'layouts/messages' %>
  <% end %>
  <% if !current_user %>
    <%= render 'users/new' %>
  <% end %>
<div class ="container hero-unit main-content">

  <%= yield %>
</div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/questions/index.html.erb
<div class = "center hero-unit">
<h2>Here is a list of questions from all our users: </h2>
 <% @questions.each do |question| %>
     <%= link_to(question.title, question, class: 'btn') %>
     <br>
     <br>
   <% end %>
   </div>

app/views/questions/new.html.erb
<div class="control-group">
<h1>Create new question</h1>

<%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
	<%= @question.errors[:title].join(',') %>
  <%= f.label :description %>
  <%= f.text_field :description %>
	<%= @question.errors[:description].join(',') %>
  <%= f.submit "Create Question", :class => 'btn btn-success' %>
<% end %>
</div>

app/views/questions/show.html.erb
this view is crazy looking, refactor it into partials.
<div class = "center hero-unit">
  <h3><%= @question.title %></h3>
  this already been handled in the layout.
  <% if flash[:notices] %>
  <p><%= flash[:notices] %></p>
  <% end %>

  <div id="question_description"><span class="votes">Votes: <%= @question_vote_total %></span> Q: <%= @question.description %>
    use helper methods. upvote_form(@question)
    <% if signed_in? %>
      <%= form_for :vote, url: question_votes_path(@question), remote: true, html: {class: "vote_create"} do |f| %>
        <%= f.button 'Upvote', name: "vote[up]", value: "true", :class => 'btn btn-success' %>
        <%= f.button 'Downvote', name: "vote[down]", value: "true", :class => 'btn btn-danger' %>
      <% end %>
    <% end %>
  </div>

  <% @answers.each_with_index do |answer, index| %>
  use helper methods. downvote_form(@question)
    <div class="answer_description"><span class="votes">Votes: <%= @answer_vote_count[index] %></span> A: <%= answer.description %>
    <% if signed_in? %>
      <%= form_for :vote, url: answer_votes_path(answer), remote: true, html: {class: "vote_create"} do |f| %>
        <%= f.button 'Upvote', name: "vote[up]", value: "true", :class => 'btn btn-success' %>
        <%= f.button 'Downvote', name: "vote[down]", value: "true", :class => 'btn btn-danger' %>
      <% end %>
    <% end %>
    </div>
  <% end %>

  <% if signed_in? %>
    <%= form_for(:answer, url: "/questions/#{@question.id}/answers") do |f| %>

      <%= f.label :description %>
      <%= f.text_field :description %>
      <%= flash[:error] %>

      <%= f.submit "Answer!", :class => 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>

app/views/users/_new.html.erb
<div class='modal' id='myModal'>
  <div class='modal-body'>
    <div class='modal-header'>
        <% provide(:title, 'Sign up') %>
        <h1>Create an account</h1>
    </div>
    <%= form_for User.new, :html => { :class => 'form-horizonal'} do |f| %>

      <div class= "center control-group">
        <div class="controls">
          <%= f.text_field :name, :placeholder => "Name", :class => 'text_field' %>
        </div>
      </div>

      <div class="center control-group">
        <div class="controls">
          <%= f.text_field :email, :placeholder => "Email",:class => 'text_field' %>
  
        </div>
      </div>

      <div class="center control-group">
        <div class="controls">
          <%= f.password_field :password,:placeholder => "Password",:class => 'text_field' %>
 
        </div>
      </div>

      <div class="center control-group">
        <%= f.submit "Sign me up!", :class => 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class = "center hero-unit">

	<%= link_to "Ask Question", new_question_path, class: 'btn btn-success'   %>
<!-- Welcome User name -->
	<h1>Welcome <%=@user.name.capitalize %>!</h1>
	<br><br>

	<h2>My questions are the followings:</h2>
<!-- List of questions -->
	<% @questions.each do |q| %>
		<tr> 
  		<td><%= link_to(q.title, q) %></td>
		</tr>
		<br>
	<%end%>


<!-- answers of users -->
	<br><br>
	<h2>My answers are: </h2>

	<% @answers.each do |a| %>
		<br>
		<%=link_to a.description, a.question %>
	<%end%>
</div>